### ISSUE TITLE
Input lag compared to other system cores

### ISSUE THREAD

**Issue by Adam7288** [libretro/snes9x-next#61]
Independent of retroarch, gpu, os settings etc, apples-to-apples comparison to other cores for different systems, this core produces massive input lag.

Worth nothing: all SNES cores produce much higher input lag than other cores, including systems much newer such as psx and n64. 

Racking my brain, what is unique about the SNES architecture, is it the custom Sony sound chip (SPC700)? Or possibly the poorly documented GPU?

Other anecdotal evidence - http://libretro.com/forums/showthread.php?t=3603

I have taken a slow motion video with iphone to demonstrate the issue. I am going to save you the trouble and tell you I have spent hours eliminating all possible causes of the lag, from the obvious to the not-so-obvious.

http://tinypic.com/player.php?v=eah4rc%3E&s=8#.Vg4S4_lVhBc

In any case, SNES gaming requires responsive input to be satisfying and accurate. Interested in any thoughts on this matter.

**Comment by faroit** [comment]
:+1:

**Comment by Brunnis** [comment]
One frame of input lag was removed in this pull request: [https://github.com/libretro/snes9x-next/pull/75](https://github.com/libretro/snes9x-next/pull/75)

The snes9x-next was actually not slower, input lag wise, than the other SNES cores such as snes9x, bsnes and bsnes-mercury. However all of these cores suffered from an extra frame of input lag compared to, for example, NES emulators. This was due to an issue with when the emulator main loop was exit during a frame interval. By adjusting the exit point, all of these SNES cores got their input lag reduced by one frame.

The SNES cores are now on the same level, input lag wise, as the NES cores (fceumm, Nestopia). Taking the host system out of the equation, the emulators themselves now usually need 2 or 3 frames to respond to input (i.e. before a visible change is seen). This appears to be built into the original consoles/games themselves and not something the emulators can "fix".

This issue should therefore be closed.

**Comment by twinaphex** [comment]
Hi there Brunnis,

would you be able to look into backporting a similar patch for CatSFC? It is a SNES9x 1.43-era fork.

**Comment by Brunnis** [comment]
Yeah, I can take a look at it. Might not have time right now, but I'll try to do it as soon as I have some time to spare.

**Comment by twinaphex** [comment]
I think we can close this now. The CATSFC request remains open though.
